//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCassa.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билет
    {
        public int КодБилета { get; set; }
        public Nullable<int> Посетитель { get; set; }
        public int Выставка { get; set; }
        public string УникальныйКод { get; set; }
        public Nullable<int> БилетОформил { get; set; }
    
        public virtual Выставка Выставка1 { get; set; }
        public virtual Посетитель Посетитель1 { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
