//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusCassa.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Экспонат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Экспонат()
        {
            this.ЭкспонатВыставка = new HashSet<ЭкспонатВыставка>();
        }
    
        public int Код { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public System.DateTime ДатаОбнаружения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭкспонатВыставка> ЭкспонатВыставка { get; set; }
    }
}
